# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9500f435bcc036887c1dcf8b9eb72312f34c382b01bcf92dc257e6ffe23d9f9647519a37333fdfbeae538a41e2dd23a9b2d201705d3f1bc2b51d0be9178d6f74

test:
  secret_key_base: 9cade5655a15b89202fcc8ea19ff54e164953cd9ab9d26b910e48c4a8e2d7b8f3009b3f1bb574a905456813caf58cb048a4ee759c5dde8eb6b42c3f9bef71363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
